// Code generated by command: go run generate.go -out add.s -stubs stub.go. DO NOT EDIT.

//go:build amd64

package asm

//go:noescape
func FindMatches(fingerprints *[16]uint8, fingerprint uint64) (bitmask uint32)
